### ISSUE TITLE
Paper writing tasks

### ISSUE THREAD

**Issue by rozsasarpi** [TNO/shear_calibration#1]
This is a master issue to list tasks and monitor the progress (GitHub does not support private issues, nor due dates so it is somewhat limited). Bigger tasks should get their own issues that are referenced here.

## Code and data

Migrate the code to GitHub (can start fresh (without carrying over the commit histories because they are not that informative).

* [x] custom FERUM on GitHub: done; [custom_FERUM](https://github.com/TNO/custom_FERUM)
* model uncertainty 
   * [x] check and clean up the code 626c74c
   * [x] publication ready plots 626c74c
   * [x] share it on GitHub 626c74c, #4
* reliability-based calibration code
   * [x] check and clean up the code #4 
   * [x] harmonize inputs: paper and Ben's thesis: no harmonization, most of the references were incorrect or "shallow", did find the references independently
   * [x] publication ready plots
   * [x] share it on GitHub #4 
* random variable algebra (python)
   * [x] check and clean up the code #4
   * [x] share it on GitHub #4
* R code and shiny app for visualizing calibration results
   * [x] create and update [repo](https://github.com/TNO/shear_calibration_shiny); https://github.com/TNO/shear_calibration_shiny/issues/4; https://github.com/TNO/shear_calibration_shiny/pull/1
   * [x] host the shiny app online (can be used from a browser): done using GitHub Actions and [shinyapps.io](https://www.shinyapps.io/) (free account)
* is there something that should not be made public?
  * [x] experimental database? cannot be shared/included in the repo
  * [x] certain shear formulas, e.g. those not yet in the standard? can be shared/included in the repo

## Writing

* [x] review current text (mostly prepared by Yuguang)
* [x] revise the main structure (sections) #2 
* writing
  * [x] section 5.2.2 (model uncertainty) and move to an annex. 
  * [x] ch. 6. 
  * [x] ch. 7.
  * [x] ch. 8
* [x] check the Spanish paper

**Comment by slobbeat** [comment]
I checked the Spanish paper (and other recent publications on reliability-based calibrations). See a brief summary here:
https://1drv.ms/w/s!AtHzYdA5fnr1enKfiHddHDUh4Tk?e=Btjp44

The work in the Spanish paper has quite some differences compared to ours, so I would not be surprised by different outcomes.

**Comment by rozsasarpi** [comment]
I close this since we have a complete draft. Let's open separate issues for refinements and other required changes.
